# Generated by Django 4.2.1 on 2023-06-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_device',
            field=models.CharField(blank=True, db_column='customer', max_length=150, null=True, verbose_name='Device ID'),
        ),
    ]
