# Generated by Django 4.2.1 on 2023-06-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_customer_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(db_column='quantity', default=0, verbose_name='Quantity'),
        ),
    ]
