# Generated by Django 4.2.1 on 2023-07-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel',
            field=models.BooleanField(db_column='cancel', default=False, verbose_name='Designates whether order is cancelled or not'),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(db_column='complete', default=False, verbose_name='Designates whwther this order is complete or not'),
        ),
    ]
